"""migration init

Revision ID: aa932f8a104d
Revises: 
Create Date: 2024-12-01 13:23:06.795595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa932f8a104d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('senha', sa.String(length=128), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('saldo', sa.Float(), nullable=True),
    sa.Column('is_moderador', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('valor_cota', sa.Float(), nullable=False),
    sa.Column('data_inicio_apostas', sa.DateTime(), nullable=False),
    sa.Column('data_fim_apostas', sa.DateTime(), nullable=False),
    sa.Column('data_ocorrencia', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resultado', sa.String(length=10), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['criado_por'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=True),
    sa.Column('detalhes', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('evento_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('tipo_aposta', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['evento_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bets')
    op.drop_table('transactions')
    op.drop_table('events')
    op.drop_table('users')
    # ### end Alembic commands ###
